"""Add template_id and used_ai to Resume model

Revision ID: 9efc51bf700f
Revises: 5e1b49953110
Create Date: 2026-03-15 01:43:11.953443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efc51bf700f'
down_revision = '5e1b49953110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('used_ai', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('used_ai')
        batch_op.drop_column('template_id')

    # ### end Alembic commands ###
